### ISSUE TITLE
"gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by ka3a4ok** [jpoirier/gortlsdr#19]
I get
> exec:  "gcc": executable file not found in %PATH%
message after  go install github.com/jpoirier/gortlsdr command

OS: Windows 7 64 bit

**Comment by jpoirier** [comment]
It appears you're missing the required gcc C compiler. You can install gcc
via MinGW (http://www.mingw.org), but be sure the bin folder where gcc.exe
lives gets set in your path environment variable. I believe the MinGW
installer asks if you'd like to add the executables folder to your path.

-joe

**Comment by jpoirier** [comment]
assuming putting gcc in path worked so closing

**Comment by aleafboat** [comment]
you can run liunx
