### ISSUE TITLE
Support for older versions of rtl-sdr

### ISSUE THREAD

**Issue by djadala** [jpoirier/gortlsdr#27]
https://github.com/jpoirier/gortlsdr/blob/818528503f3cf95e75ef9eaff4857216a7c0225c/rtlsdr.go#L32
Please add here:
```
#ifdef rtlsdr_set_bias_tee
static int rtlsdr_set_bias_tee_wrap(rtlsdr_dev_t* d, int i) { return rtlsdr_set_bias_tee(d,i); }
#else
static int rtlsdr_set_bias_tee_wrap(rtlsdr_dev_t* d, int i) { return -12; }
#endif
```
And call  rtlsdr_set_bias_tee_wrap instead of  rtlsdr_set_bias_tee
Thanks.

**Comment by djadala** [comment]
#14 can be fixed in same way

**Comment by jpoirier** [comment]
That won't work when librtlsdr has a rtlsdr_set_bias_tee function
declaration in rtl-sdr.h unless the name rtlsdr_set_bias_tee is defined
manually (#define rtlsdr_set_bias_tee) somewhere, e.g. in the rtl-sdr.h
header file or in the cgo comments of rtlsdr.go, or via an external build
mechanism like a make file etc...

-joe

**Comment by djadala** [comment]
You are right,
I checked only non existent function branch of #ifdef
Sorry for noise.

Close this issue ?

**Comment by jpoirier** [comment]
No problem, and thanks for having a look at it!

-joe
